export const COPY = {
  id: {
    appName: 'Satria Tani',
    tagline: 'Asuransi Padi Parametrik · Triple-Trigger',
    verifier: 'Konsol Verifier',
    coop: 'Dasbor Koperasi',
    farmer: 'Lapor Mangsa',
    activeClaims: 'Klaim Aktif',
    underReview: 'Dalam Verifikasi',
    paid: 'Telah Dibayar',
    rejected: 'Ditolak',
    triggers: 'Pemicu',
    geospatial: 'Geospasial',
    peerAttest: 'Atestasi Antar-Desa',
    pranata: 'Pranata Mangsa',
    decision: 'Keputusan Otomatis',
    payout: 'Pencairan',
    audit: 'Jejak Audit',
    fired: 'Terpicu',
    pending: 'Menunggu',
    notFired: 'Tidak Terpicu',
    member: 'Anggota',
    farmer_label: 'Petani',
    village: 'Desa',
    district: 'Kabupaten',
    province: 'Provinsi',
    season: 'Musim Tanam',
    coverage: 'Pertanggungan',
    voucher: 'Voucher',
    distributed: 'Disalurkan',
    pending_voucher: 'Tertunda',
    payouts: 'Pencairan',
    members: 'Anggota',
    addObs: 'Tambah Pengamatan',
    submit: 'Kirim',
    photo: 'Foto',
    yourTurn: 'Giliran Anda',
  },
} as const;
